[parity]
chain = "./data/spec.json"
base_path = "data/node4"

[ui]
disable = true

[network]
port = 30304
discovery = true
reserved_peers="data/reserved-peers"
nat = "none"
interface = "local"

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "personal", "traces", "rpc", "shh", "shh_pubsub"]
port = 8544

[websockets]
port = 9544

[ipc]
disable = true

[secretstore]
disable = true

[account]
unlock = ["0xf67cc5231c5858ad6cc87b105217426e17b824bb"]
password = ["config/password"]

[mining]
force_sealing = true
min_gas_price = 1000000000
gas_floor_target = "10000000"
engine_signer = "0xf67cc5231c5858ad6cc87b105217426e17b824bb"
reseal_on_txs = "none"
extra_data = "Parity"

[misc]
logging = "engine=trace,miner=trace,reward=trace"
